credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      name: Amministratore
      password: $2b$12$w0ZP7pkUxCnwd32pFSZFae3o6dKYkXyOItjGpIKgjHAYU88k2WJQm # To be replaced with hashed password
    lucadg:
      email: rbriggs@gmail.com
      name: ldg
      password: $2b$12$w0ZP7pkUxCnwd32pFSZFae3o6dKYkXyOItjGpIKgjHAYU88k2WJQm # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com